theme = "hugo-theme-slim"
baseURL = "/"
languageCode = "en-us"
title = "Batteries Not Included"

# Parameters
[params]
  subtitle = "IID observations from a universe of data"
  summary = true
  githubid = "blairj09"
  twitterid = "Blair09M"
  
[permalinks]
    post = "/:year/:month/:slug/"

#[menu]
#[[menu.main]]
#  name = "Projects"
#  url = "/projects/"
#  weight = 1