theme = "hugo-theme-slim"
baseURL = "https://batteriesnotincluded-dev.netlify.com/"
languageCode = "en-us"
title = "Batteries Not Included"

# Parameters
[params]
  subtitle = "IID observations from a universe of data"
  summary = true
  githubid = "blairj09"
  twitterid = "Blair09M"
  
[permalinks]
    post = "/:year/:month/:slug/"

#[[menu.main]]
#  name = "Projects"
#  url = "/projects/"
#  weight = 3
  
[[menu.main]]
  name = "Résumé"
  url = "/resume/"
  weight = 2
  
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1